### ISSUE TITLE
Error when deploying to Goeri network

### ISSUE THREAD

**Issue by jerryponnoth** [PatrickAlphaC/ethers-simple-storage-fcc#49]
I am getting this error
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32000,\"message\":\"gas required exceeds allowance (0)\"

**Comment by TechnoRahmon** [comment]
can you provide more info about your code, 
where/when does this error occur?

**Comment by TechnoRahmon** [comment]
hi @jerryponnoth 

I got the same error right now when I tried to deploy my contract into **GOERLI** test network on **Alchemy**.

in my case, the issue was that I used a **Ganache** local **private key**,
solved:  **be sure to use your MetaMask wallet private key** 

so the node will throw that error even if the transaction would legitimately fails. 
please check the **ethers js doc** [UNPREDICTABLE_GAS_LIMIT](https://docs.ethers.io/v5/troubleshooting/errors/#help-UNPREDICTABLE_GAS_LIMIT)

**Comment by jerryponnoth** [comment]
Thank you @TechnoRahmon  for checking this. I was using metamask but was unable to add some Ethers using Ether faucets available out there. I deleted all the Georli metamask updates and created one from scratch. Then the Alchemy Ether faucets worked and transferred .1 ethers. I think this has to do with my metamask not having enough ethers to perform the transaction. Thank you chiming in . am good now

**Comment by TechnoRahmon** [comment]
> Thank you @TechnoRahmon for checking this. I was using metamask but was unable to add some Ethers using Ether faucets available out there. I deleted all the Georli metamask updates and created one from scratch. Then the Alchemy Ether faucets worked and transferred .1 ethers. I think this has to do with my metamask not having enough ethers to perform the transaction. Thank you chiming in . am good now

I understand 
you're welcome 😄
