### ISSUE TITLE
Error when calling the method in contract

### ISSUE THREAD

**Issue by brunovu20** [PatrickAlphaC/ethers-simple-storage-fcc#77]
When I try this line on my local with ganache:

`let transactionResponse = await contract.store(7)`

I have this message

Error: could not coalesce error (error={ "code": -32000, "message": "the tx doesn't have the correct nonce. account has nonce of: 17 tx has nonce of: 16", "stack": "Error: the tx doesn't have the correct nonce

Does anyone have same problem with me ?

**Comment by brunovu20** [comment]
I find the solution, because I called many times in short time, so that can not detect number of transaction

**Comment by Varun-Kolanu** [comment]
I ran into a similar problem. 
I have added a wait for 100ms for the transaction to be updated. But this 100ms was trial and error. Isn't there any method to wait till the nonce get updated? Because for different testnets or mainnets, and according to the crowd in blochain, the waiting time may significantly vary right?

My code:
```javascript
function wait(ms) {
    return new Promise(resolve => {
        setTimeout(resolve, ms);
    });
}

// Before the next transaction:
await wait(100);
```
